title: Michael Mogilevsky APCSA Final Project
author: Michael Mogilevsky
email: mmmplayer16@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome! Here, I'm going to talk about myself.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
